### ISSUE TITLE
On Windows Getting Started/Basic Usage doesn't compile.

### ISSUE THREAD

**Issue by tomshaw** [kt3k/packup#4]
I'm unable to get the Basic Usage app to compile `without` error:

`error: Do not know how to load path: deno: c:\Users\me\Desktop\myapp\main.ts`

Nothing there but the index/main.ts. Running Windows 10, deno 1.11.1, packup v0.0.12

**Comment by differentsmoke** [comment]
I am having the same issue. It does work with the Windows Subsystem for Linux.

**Comment by differentsmoke** [comment]
**Update**:

@tomshaw The issue seems to be _specific_ to **esbuild**. Running `packup serve index.html --bundler swc` works as expected (*).

(*) _Windows also has some issues with orphaned versions of Deno running in the background that may cause issues with websockets, but this isn't a packup specific problem._

**Comment by kt3k** [comment]
@tomshaw @differentsmoke Thank you for reporting! I'm looking into it.

**Comment by kt3k** [comment]
@tomshaw @differentsmoke We released `v0.0.13`, which potentially fixes this issue. Please let me know if it works for you or not.

**Comment by differentsmoke** [comment]
I was able to run all of the examples.

**Comment by kt3k** [comment]
@differentsmoke Thank you for checking!

**Comment by tomshaw** [comment]
Appreciate `packup serve index.html --bundler swc` solves issue. Thank you guys,
